name: 'Actions Workflow'
on:
  workflow_dispatch: {}
  pull_request:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  install-and-build:
    name: Install and Build GHA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install

      - run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  test-dotnet-stack:
    needs: install-and-build
    runs-on: ${{ matrix.os }}
    name: Dotnet ${{ matrix.command }} on ${{ matrix.os }}
    strategy:
      matrix:
        command: [raw]
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Generate args
        id: args
        shell: bash
        run: |
          if [[ "${{ matrix.command }}" == "raw" ]]; then
            echo "args=up,--yes,-s dev,--cwd,.github/test-stacks/dotnet,-c '{name: {value: my-pet, secret: false}}'" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [[ "${{ matrix.command }}" != "preview" ]]; then
            echo "args=${{ matrix.command }},--yes,-s dev,--cwd,.github/test-stacks/dotnet,-c,'{name: {value: my-pet, secret: false}}'" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "args=${{ matrix.command }},-s dev,--cwd,.github/test-stacks/dotnet,-c,'{name: {value: my-pet, secret: false}}'" >> $GITHUB_OUTPUT

      - uses: ./
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
        with:
          command: ${{ matrix.command }}
          args: "${{ steps.args.outputs.args }}"
          cloud-url: file://~
          upsert: true
          stack-name: dev
          work-dir: .github/test-stacks/dotnet
          config-map: "{name: {value: my-pet, secret: false}}"
